package net.tslat.aoa3.common.registration.item;

import net.minecraft.core.component.DataComponents;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Rarity;
import net.neoforged.neoforge.registries.DeferredItem;
import net.tslat.aoa3.common.registration.AoATags;
import net.tslat.aoa3.content.item.datacomponent.*;
import net.tslat.aoa3.content.item.weapon.blaster.*;
import net.tslat.aoa3.content.item.weapon.bow.*;
import net.tslat.aoa3.content.item.weapon.cannon.*;
import net.tslat.aoa3.content.item.weapon.crossbow.*;
import net.tslat.aoa3.content.item.weapon.greatblade.*;
import net.tslat.aoa3.content.item.weapon.gun.*;
import net.tslat.aoa3.content.item.weapon.maul.*;
import net.tslat.aoa3.content.item.weapon.shotgun.*;
import net.tslat.aoa3.content.item.weapon.sniper.Terminator;
import net.tslat.aoa3.content.item.weapon.sniper.*;
import net.tslat.aoa3.content.item.weapon.staff.*;
import net.tslat.aoa3.content.item.weapon.sword.*;
import net.tslat.aoa3.content.item.weapon.thrown.*;
import net.tslat.aoa3.content.item.weapon.vulcane.*;
import net.tslat.aoa3.library.constant.AttackSpeed;
import org.jetbrains.annotations.Nullable;

import java.util.function.Supplier;

public final class AoAWeapons {
	public static void init() {}

	public static final DeferredItem<Item> BARON_SWORD = registerWeapon("baron_sword", () -> new BaronSword(AoATiers.BARON, BaseSword.baseProperties(AoATiers.BARON)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> BLOODFURY = registerWeapon("bloodfury", () -> new BaseSword(AoATiers.BLOODFURY, BaseSword.baseProperties(AoATiers.BLOODFURY, AttackSpeed.forAttacksPerSecond(1.8f))), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> BLOODSTONE_SWORD = registerWeapon("bloodstone_sword", () -> new BaseSword(AoATiers.BLOODSTONE, BaseSword.baseProperties(AoATiers.BLOODSTONE, AttackSpeed.SWORD)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> CANDLEFIRE_SWORD = registerWeapon("candlefire_sword", () -> new CandlefireSword(AoATiers.CANDLEFIRE, BaseSword.baseProperties(AoATiers.CANDLEFIRE)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> CARAMEL_CARVER = registerWeapon("caramel_carver", () -> new CaramelCarver(AoATiers.CARAMEL_CARVER, BaseSword.baseProperties(AoATiers.CARAMEL_CARVER)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> CORALSTORM_SWORD = registerWeapon("coralstorm_sword", () -> new CoralstormSword(AoATiers.CORALSTORM, BaseSword.baseProperties(AoATiers.CORALSTORM)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> CREEPIFIED_SWORD = registerWeapon("creepified_sword", () -> new CreepifiedSword(AoATiers.CREEPIFIED, BaseSword.baseProperties(AoATiers.CREEPIFIED)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> CRYSTALLITE_SWORD = registerWeapon("crystallite_sword", () -> new BaseSword(AoATiers.CRYSTALLITE, BaseSword.baseProperties(AoATiers.CRYSTALLITE, AttackSpeed.forAttacksPerSecond(1.7f))), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> EMBERSTONE_SWORD = registerWeapon("emberstone_sword", () -> new EmberstoneSword(AoATiers.EMBERSTONE, BaseSword.baseProperties(AoATiers.EMBERSTONE)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> EXPLOCHRON_SWORD = registerWeapon("explochron_sword", () -> new ExplochronSword(AoATiers.EXPLOCHRON, BaseSword.baseProperties(AoATiers.EXPLOCHRON)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> FIREBORNE_SWORD = registerWeapon("fireborne_sword", () -> new FireborneSword(AoATiers.FIREBORNE, BaseSword.baseProperties(AoATiers.FIREBORNE)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> GUARDIANS_SWORD = registerWeapon("guardians_sword", () -> new GuardiansSword(AoATiers.GUARDIAN, BaseSword.baseProperties(AoATiers.GUARDIAN).component(AoADataComponents.CHARGE, 0f)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> HARVESTER_SWORD = registerWeapon("harvester_sword", () -> new HarvesterSword(AoATiers.HARVESTER, BaseSword.baseProperties(AoATiers.HARVESTER)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> HOLY_SWORD = registerWeapon("holy_sword", () -> new HolySword(AoATiers.HOLY, BaseSword.baseProperties(AoATiers.HOLY, AttackSpeed.TRIPLE).rarity(Rarity.EPIC)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> ILLUSION_SWORD = registerWeapon("illusion_sword", () -> new IllusionSword(AoATiers.ILLUSION, BaseSword.baseProperties(AoATiers.ILLUSION)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> JADE_SWORD = registerWeapon("jade_sword", () -> new BaseSword(AoATiers.JADE, BaseSword.baseProperties(AoATiers.JADE, AttackSpeed.SWORD)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> LEGBONE_SWORD = registerWeapon("legbone_sword", () -> new LegboneSword(AoATiers.LEGBONE, BaseSword.baseProperties(AoATiers.LEGBONE)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> LIGHTS_WAY = registerWeapon("lights_way", () -> new BaseSword(AoATiers.LIGHTS_WAY, BaseSword.baseProperties(AoATiers.LIGHTS_WAY, AttackSpeed.DOUBLE)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> LIMONITE_SWORD = registerWeapon("limonite_sword", () -> new BaseSword(AoATiers.LIMONITE, BaseSword.baseProperties(AoATiers.LIMONITE, AttackSpeed.SWORD)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> NETHENGEIC_SWORD = registerWeapon("nethengeic_sword", () -> new NethengeicSword(AoATiers.NETHENGEIC, BaseSword.baseProperties(AoATiers.NETHENGEIC)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> PRIMAL_SWORD = registerWeapon("primal_sword", () -> new PrimalSword(AoATiers.PRIMAL, BaseSword.baseProperties(AoATiers.PRIMAL)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> ROCKBASHER_SWORD = registerWeapon("rockbasher_sword", () -> new RockbasherSword(AoATiers.PRIMAL, BaseSword.baseProperties(AoATiers.PRIMAL)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> ROCK_PICK_SWORD = registerWeapon("rock_pick_sword", () -> new RockPickSword(AoATiers.ROCK_PICK, BaseSword.baseProperties(AoATiers.ROCK_PICK)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> ROSIDIAN_SWORD = registerWeapon("rosidian_sword", () -> new RosidianSword(AoATiers.ROSIDIAN, BaseSword.baseProperties(AoATiers.ROSIDIAN)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> RUNIC_SWORD = registerWeapon("runic_sword", () -> new RunicSword(AoATiers.RUNIC, BaseSword.baseProperties(AoATiers.RUNIC)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> SHADOW_SWORD = registerWeapon("shadow_sword", () -> new BaseSword(AoATiers.SHADOW, BaseSword.baseProperties(AoATiers.SHADOW, AttackSpeed.SWORD)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> SHROOMUS_SWORD = registerWeapon("shroomus_sword", () -> new ShroomusSword(AoATiers.SHROOMUS, BaseSword.baseProperties(AoATiers.SHROOMUS)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> SKELETAL_SWORD = registerWeapon("skeletal_sword", () -> new BaseSword(AoATiers.SKELETAL, BaseSword.baseProperties(AoATiers.SKELETAL, 1, AttackSpeed.forAttacksPerSecond(2))), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> SUPREMACY_SWORD = registerWeapon("supremacy_sword", () -> new SupremacySword(AoATiers.SUPREMACY, BaseSword.baseProperties(AoATiers.SUPREMACY)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> SWEET_SWORD = registerWeapon("sweet_sword", () -> new SweetSword(AoATiers.SWEET, BaseSword.baseProperties(AoATiers.SWEET)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> TROLL_BASHER_AXE = registerWeapon("troll_basher_axe", () -> new TrollBasherAxe(AoATiers.TROLL_BASHER, BaseSword.baseProperties(AoATiers.TROLL_BASHER)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> ULTRAFLAME = registerWeapon("ultraflame", () -> new Ultraflame(AoATiers.ULTRAFLAME, BaseSword.baseProperties(AoATiers.ULTRAFLAME)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> VOID_SWORD = registerWeapon("void_sword", () -> new VoidSword(AoATiers.VOID, BaseSword.baseProperties(AoATiers.VOID)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredItem<Item> FAUNAMANCERS_BLADE = registerWeapon("faunamancers_blade", () -> new FaunamancersBlade(AoATiers.FAUNAMANCERS_BLADE, BaseSword.baseProperties(AoATiers.FAUNAMANCERS_BLADE, AttackSpeed.DOUBLE)), AoACreativeModeTabs.SWORDS.getKey());

	public static final DeferredItem<Item> BARON_GREATBLADE = registerWeapon("baron_greatblade", () -> new BaronGreatblade(AoATiers.BARON_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.BARON_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> BLOODLURKER = registerWeapon("bloodlurker", () -> new BaseGreatblade(AoATiers.BLOODLURKER_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.BLOODLURKER_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> CANDY_BLADE = registerWeapon("candy_blade", () -> new CandyBlade(AoATiers.CANDY_BLADE_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.CANDY_BLADE_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> CORAL_GREATBLADE = registerWeapon("coral_greatblade", () -> new BaseGreatblade(AoATiers.CORAL_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.CORAL_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> COTTON_CRUSHER = registerWeapon("cotton_crusher", () -> new CottonCrusher(AoATiers.COTTON_CRUSHER_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.COTTON_CRUSHER_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> CREEPOID_GREATBLADE = registerWeapon("creepoid_greatblade", () -> new CreepoidGreatblade(AoATiers.CREEPOID_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.CREEPOID_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> CRYSTAL_GREATBLADE = registerWeapon("crystal_greatblade", () -> new CrystalGreatblade(AoATiers.CRYSTAL_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.CRYSTAL_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> EREBON_SCYTHE = registerWeapon("erebon_scythe", () -> new ErebonScythe(AoATiers.EREBON_SCYTHE, BaseGreatblade.baseProperties(AoATiers.EREBON_SCYTHE, AttackSpeed.forAttacksPerSecond(1))), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> GODS_GREATBLADE = registerWeapon("gods_greatblade", () -> new BaseGreatblade(AoATiers.GODS_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.GODS_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> GOOFY_GREATBLADE = registerWeapon("goofy_greatblade", () -> new GoofyGreatblade(AoATiers.GOOFY_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.GOOFY_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> HAUNTED_GREATBLADE = registerWeapon("haunted_greatblade", () -> new HauntedGreatblade(AoATiers.HAUNTED_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.HAUNTED_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> KNIGHTS_GUARD = registerWeapon("knights_guard", () -> new KnightsGuard(AoATiers.KNIGHTS_GUARD_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.KNIGHTS_GUARD_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> LELYETIAN_GREATBLADE = registerWeapon("lelyetian_greatblade", () -> new LelyetianGreatblade(AoATiers.LELYETIAN_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.LELYETIAN_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> LUNAR_GREATBLADE = registerWeapon("lunar_greatblade", () -> new LunarGreatblade(AoATiers.LUNAR_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.LUNAR_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> LUXON_SCYTHE = registerWeapon("luxon_scythe", () -> new LuxonScythe(AoATiers.LUXON_SCYTHE, BaseGreatblade.baseProperties(AoATiers.LUXON_SCYTHE, AttackSpeed.forAttacksPerSecond(1.2f))), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> LYONIC_GREATBLADE = registerWeapon("lyonic_greatblade", () -> new BaseGreatblade(AoATiers.LYONIC_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.LYONIC_GREATBLADE, AttackSpeed.forAttacksPerSecond(0.9f))), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> MILLENNIUM_GREATBLADE = registerWeapon("millennium_greatblade", () -> new MillenniumGreatblade(AoATiers.MILLENNIUM_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.MILLENNIUM_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> NOXIOUS_GREATBLADE = registerWeapon("noxious_greatblade", () -> new NoxiousGreatblade(AoATiers.NOXIOUS_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.NOXIOUS_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> PLUTON_SCYTHE = registerWeapon("pluton_scythe", () -> new PlutonScythe(AoATiers.PLUTON_SCYTHE, PlutonScythe.baseProperties(AoATiers.PLUTON_SCYTHE, AttackSpeed.forAttacksPerSecond(1))), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> PRIMORDIAL_GREATBLADE = registerWeapon("primordial_greatblade", () -> new PrimordialGreatblade(AoATiers.PRIMORDIAL_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.PRIMORDIAL_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> ROSIDIAN_GREATBLADE = registerWeapon("rosidian_greatblade", () -> new RosidianGreatblade(AoATiers.ROSIDIAN_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.ROSIDIAN_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> ROYAL_GREATBLADE = registerWeapon("royal_greatblade", () -> new BaseGreatblade(AoATiers.ROYAL_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.ROYAL_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> RUNIC_GREATBLADE = registerWeapon("runic_greatblade", () -> new RunicGreatblade(AoATiers.RUNIC_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.RUNIC_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> SELYAN_SCYTHE = registerWeapon("selyan_scythe", () -> new SelyanScythe(AoATiers.SELYAN_SCYTHE, BaseGreatblade.baseProperties(AoATiers.SELYAN_SCYTHE, AttackSpeed.forAttacksPerSecond(1))), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> SHROOMIC_GREATBLADE = registerWeapon("shroomic_greatblade", () -> new ShroomicGreatblade(AoATiers.SHROOMIC_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.SHROOMIC_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> SHYRE_SWORD = registerWeapon("shyre_sword", () -> new ShyreSword(AoATiers.SHYRE_SWORD_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.SHYRE_SWORD_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> SUBTERRANEAN_GREATBLADE = registerWeapon("subterranean_greatblade", () -> new SubterraneanGreatblade(AoATiers.SUBTERRANEAN_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.SUBTERRANEAN_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> TIDAL_GREATBLADE = registerWeapon("tidal_greatblade", () -> new TidalGreatblade(AoATiers.TIDAL_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.TIDAL_GREATBLADE).rarity(Rarity.RARE)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredItem<Item> UNDERWORLD_GREATBLADE = registerWeapon("underworld_greatblade", () -> new UnderworldGreatblade(AoATiers.UNDERWORLD_GREATBLADE, BaseGreatblade.baseProperties(AoATiers.UNDERWORLD_GREATBLADE)), AoACreativeModeTabs.GREATBLADES.getKey());

	public static final DeferredItem<Item> CORALSTONE_MAUL = registerWeapon("coralstone_maul", () -> new BaseMaul(26.5f, AttackSpeed.THIRD, 8.5d, 1600), AoACreativeModeTabs.MAULS.getKey());
	public static final DeferredItem<Item> CRYSTAL_MAUL = registerWeapon("crystal_maul", CrystalMaul::new, AoACreativeModeTabs.MAULS.getKey());
	public static final DeferredItem<Item> ELECTRON_MAUL = registerWeapon("electron_maul", ElectronMaul::new, AoACreativeModeTabs.MAULS.getKey());
	public static final DeferredItem<Item> HORIZON_MAUL = registerWeapon("horizon_maul", HorizonMaul::new, AoACreativeModeTabs.MAULS.getKey());
	public static final DeferredItem<Item> VULCAMMER_MAUL = registerWeapon("vulcammer_maul", VulcammerMaul::new, AoACreativeModeTabs.MAULS.getKey());

	public static final DeferredItem<Item> ABOMINATOR = registerWeapon("abominator", () -> new Abominator(GunStats.of(2.625f, 3, 0.8f, 0.8540909f).durability(4720)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> APOCO_ASSAULT_RIFLE = registerWeapon("apoco_assault_rifle", () -> new ApocoAssaultRifle(GunStats.of(5.625f, 6, 0.6f, 0.85795456f).durability(5920)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> APOCO_RIFLE = registerWeapon("apoco_rifle", () -> new ApocoRifle(GunStats.of(2.5f, 6, 1, 0.82575756f).durability(5960)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> AQUA_MAGNUM = registerWeapon("aqua_magnum", () -> new AquaMagnum(GunStats.of(2.0625f, 2, 0.95f, 0.86375f).durability(6080)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> ARTIFACT = registerWeapon("artifact", () -> new Artifact(GunStats.of(10f, 5, 0.65f, 0.9236364f).durability(6000)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> BARONATOR = registerWeapon("baronator", () -> new Baronator(GunStats.of(3f, 5, 0.95f, 0.8370909f).durability(2480)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> BAYONETTE_RIFLE = registerWeapon("bayonette_rifle", () -> new BayonetteRifle(GunStats.of(3.4375f, 5, 0.85f, 0.84250003f).durability(2520).attributes(BayonetteRifle.createAttributes())), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> BIG_TOP = registerWeapon("big_top", () -> new BigTop(GunStats.of(3.125f, 4, 0.9f, 0.84829545f).durability(3680)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> BLOOD_IRON = registerWeapon("blood_iron", () -> new BloodIron(GunStats.of(6.125f, 8, 0.55f, 0.84732956f).durability(3480)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> CHAIN_WRECKER = registerWeapon("chain_wrecker", () -> new ChainWrecker(GunStats.of(1.5f, 2, 1.2f, 0.84636366f).durability(3840)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> CHILLI_CHUGGER = registerWeapon("chilli_chugger", () -> new ChilliChugger(GunStats.of(3f, 4, 0.5f, 0.84636366f).durability(3560)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> CLOWNERSHOT = registerWeapon("clownershot", () -> new Clownershot(GunStats.of(2f, 4, 1.3f, 0.83090913f).durability(5880)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> CONSTRUCT = registerWeapon("construct", () -> new Construct(GunStats.of(2.375f, 3, 0.9f, 0.8489394f).durability(3640)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> CORAL_CLOGGER = registerWeapon("coral_clogger", () -> new CoralClogger(GunStats.of(9.075f, 10, 0.45f, 0.8561f).durability(2000)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> CORE_RIFLE = registerWeapon("core_rifle", () -> new CoreRifle(GunStats.of(1.875f, 3, 1f, 0.8386364f).durability(2520)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> CRYSTAL_CARVER = registerWeapon("crystal_carver", () -> new CrystalCarver(GunStats.of(3f, 4, 0.85f, 0.84636366f).durability(3480)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> CYCLONE = registerWeapon("cyclone", () -> new Cyclone(GunStats.of(2.375f, 3, 1f, 0.8489394f).durability(4400)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> DARKENER = registerWeapon("darkener", () -> new Darkener(GunStats.of(2.875f, 3, 0.9f, 0.85924244f).durability(6040)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> DART_GUN = registerWeapon("dart_gun", () -> new DartGun(GunStats.of(4.675f, 5, 0.2f, 0.8578f).durability(4520)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> DESTRUCTION_RIFLE = registerWeapon("destruction_rifle", () -> new DestructionRifle(GunStats.of(3.125f, 5, 1f, 0.8386364f).durability(2440)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> DISCHARGE_RIFLE = registerWeapon("discharge_rifle", () -> new DischargeRifle(GunStats.of(1.25f, 6, 3f, 0.8128788f).durability(2280)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> DRACO = registerWeapon("draco", () -> new Draco(GunStats.of(3.75f, 4, 0.75f, 0.85795456f).durability(5560)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> DRAGILATOR = registerWeapon("dragilator", () -> new Dragilator(GunStats.of(1.625f, 2, 1.1f, 0.8502273f).durability(4480)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> DUSTOMETER = registerWeapon("dustometer", () -> new Dustometer(GunStats.of(5.25f, 6, 0.65f, 0.8540909f).durability(4720)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> ECHO_GULL = registerWeapon("echo_gull", () -> new EchoGull(GunStats.of(4.375f, 7, 0.85f, 0.8386364f).durability(2320)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> ELECTINATOR = registerWeapon("electinator", () -> new Electinator(GunStats.of(1.625f, 2, 1.1f, 0.8502273f).durability(4480)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> FLAME_WRECKER = registerWeapon("flame_wrecker", () -> new FlameWrecker(GunStats.of(1.875f, 2, 1.15f, 0.85795456f).durability(6120)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> FLAMING_FURY = registerWeapon("flaming_fury", () -> new FlamingFury(GunStats.of(5.125f, 7, 0.6f, 0.8452597f).durability(3440)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> FLORO_RIFLE = registerWeapon("floro_rifle", () -> new FloroRifle(GunStats.of(3.75f, 4, 0.75f, 0.85795456f).durability(6000)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> FLOWERS_FURY = registerWeapon("flowers_fury", () -> new FlowersFury(GunStats.of(3.25f, 4, 0.9f, 0.8502273f).durability(4400)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> FROSTICATOR = registerWeapon("frosticator", () -> new Frosticator(GunStats.of(1.625f, 2, 1.1f, 0.8502273f).durability(4480)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> GARDENER = registerWeapon("gardener", () -> new Gardener(GunStats.of(1.75f, 3, 1f, 0.83606064f).durability(2520).rarity(Rarity.RARE)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> GAUGE_RIFLE = registerWeapon("gauge_rifle", () -> new GaugeRifle(GunStats.of(5.625f, 9, 0.85f, 0.8386364f).durability(2360)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> GERMINATOR = registerWeapon("germinator", () -> new Germinator(GunStats.of(1.625f, 2, 1.1f, 0.8502273f).durability(4480)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> GOLDEN_FURY = registerWeapon("golden_fury", () -> new GoldenFury(GunStats.of(6.5f, 7, 0.45f, 0.8574026f).durability(6080)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> HAPPY_HAUNTER = registerWeapon("happy_haunter", () -> new HappyHaunter(GunStats.of(2.875f, 3, 0.85f, 0.85924244f).durability(6040)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> HAUNTER_RIFLE = registerWeapon("haunter_rifle", () -> new HaunterRifle(GunStats.of(2.75f, 3, 0.9f, 0.8566667f).durability(5680)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> HEAT_WAVE = registerWeapon("heat_wave", () -> new HeatWave(GunStats.of(6.05f, 6, 0.8f, 0.86233336f).durability(5880)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> HIVER = registerWeapon("hiver", () -> new Hiver(GunStats.of(2.875f, 3, 1f, 0.85924244f).durability(5960)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> HOT_SHOT = registerWeapon("hot_shot", () -> new HotShot(GunStats.of(3.9875f, 6, 1f, 0.84108335f).durability(2320)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> HUNTERS_RIFLE = registerWeapon("hunters_rifle", () -> new HuntersRifle(GunStats.of(5.9125f, 7, 0.9f, 0.8522143f).durability(3600)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> IOMINATOR = registerWeapon("iominator", () -> new Iominator(GunStats.of(2.875f, 3, 0.95f, 0.85924244f).durability(6000)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> ION_REVOLVER = registerWeapon("ion_revolver", () -> new IonRevolver(GunStats.of(2.6125f, 3, 1.65f, 0.8538333f).durability(3720)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> IRO_RIFLE = registerWeapon("iro_rifle", () -> new IroRifle(GunStats.of(3.125f, 4, 0.95f, 0.84829545f).durability(3640)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> KRILINATOR = registerWeapon("krilinator", () -> new Krilinator(GunStats.of(3.75f, 5, 1.1f, 0.84636366f).durability(3600)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> LIGHT_IRON = registerWeapon("light_iron", () -> new LightIron(GunStats.of(7.625f, 8, 0.6f, 0.85892045f).durability(5880)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> LUNAR_ASSAULT_RIFLE = registerWeapon("lunar_assault_rifle", () -> new LunarAssaultRifle(GunStats.of(2.875f, 3, 0.85f, 0.85924244f).durability(5720)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> MECHANICAL_ASSAULT_RIFLE = registerWeapon("mechanical_assault_rifle", () -> new MechanicalAssaultRifle(GunStats.of(4.625f, 6, 0.85f, 0.84765154f).durability(3760)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> MEGAGUN = registerWeapon("megagun", () -> new Megagun(GunStats.of(1f, 1, 1.1f, 0.8618182f).durability(6120)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> MIASMA = registerWeapon("miasma", () -> new Miasma(GunStats.of(2.25f, 3, 1, 0.84636366f).durability(3760)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> MINIGUN = registerWeapon("minigun", () -> new Minigun(GunStats.of(0.625f, 1, 1.5f, 0.8386364f).durability(2680)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> MINT_MAGNUM = registerWeapon("mint_magnum", () -> new MintMagnum(GunStats.of(1.65f, 2, 1.25f, 0.851f).durability(3600)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> MK = registerWeapon("mk", () -> new MK(GunStats.of(3.625f, 4, 0.75f, 0.8560227f).durability(4960)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> MK_FUNG = registerWeapon("mk_fung", () -> new MKFung(GunStats.of(3.75f, 4, 0.75f, 0.85795456f).durability(5960)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> NETHENETTE_RIFLE = registerWeapon("nethenette_rifle", () -> new NethenetteRifle(GunStats.of(5.0875f, 5, 0.85f, 0.8629f).durability(6000).attributes(NethenetteRifle.createAttributes())), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> NETHENGEIC_SLUGGER = registerWeapon("nethengeic_slugger", () -> new NethengeicSlugger(GunStats.of(6.1875f, 8, 0.75f, 0.84781253f).durability(3120)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> OVERSHOT = registerWeapon("overshot", () -> new Overshot(GunStats.of(1.625f, 4, 2.1f, 0.82511365f).durability(3960)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> PRECASIAN_SLUGGER = registerWeapon("precasian_slugger", () -> new PrecasianSlugger(GunStats.of(8.1125f, 8, 0.5f, 0.8626875f).durability(5960)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> PREDATOR = registerWeapon("predator", () -> new Predator(GunStats.of(6.375f, 7, 0.45f, 0.85629874f).durability(5920)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> PREDIGUN = registerWeapon("predigun", () -> new Predigun(GunStats.of(1f, 1, 1f, 0.8618182f).durability(6120)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> PULSATOR = registerWeapon("pulsator", () -> new Pulsator(GunStats.of(6.25f, 7, 0.5f, 0.8551948f).durability(4760)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> PURITY_RIFLE = registerWeapon("purity_rifle", () -> new PurityRifle(GunStats.of(4.5f, 5, 0.75f, 0.85563636f).durability(4800)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> ROCKER_RIFLE = registerWeapon("rocker_rifle", () -> new RockerRifle(GunStats.of(2.5f, 4, 1f, 0.8386364f).durability(2520)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> ROULETTE = registerWeapon("roulette", () -> new Roulette(GunStats.of(6.1875f, 6, 0.85f, 0.86375f).durability(5880)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> SHOE_FLINGER = registerWeapon("shoe_flinger", () -> new ShoeFlinger(GunStats.of(6f, 6, 1f, 0.8618182f).durability(1600)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> SKULLETTE = registerWeapon("skullette", () -> new Skullette(GunStats.of(6.4625f, 6, 0.85f, 0.86658335f).durability(6320)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> SKULLIFACT = registerWeapon("skullifact", () -> new Skullifact(GunStats.of(10f, 5, 0.45f, 0.9236364f).durability(6280)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> SPECTACLE = registerWeapon("spectacle", () -> new Spectacle(GunStats.of(2.75f, 4, 0.85f, 0.84250003f).durability(3520)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> SPINE_GUN = registerWeapon("spine_gun", () -> new SpineGun(GunStats.of(2.875f, 3, 0.85f, 0.85924244f).durability(6040)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> SQUAD_GUN = registerWeapon("squad_gun", () -> new SquadGun(GunStats.of(2.625f, 3, 0.85f, 0.8540909f).durability(4840)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> STAMPEDE = registerWeapon("stampede", () -> new Stampede(GunStats.of(3.3f, 6, 1f, 0.834f).durability(1200)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> STORMER = registerWeapon("stormer", () -> new Stormer(GunStats.of(8f, 5, 0.45f, 0.8989091f).durability(3600)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> SUBLIMUS = registerWeapon("sublimus", () -> new Sublimus(GunStats.of(2.75f, 3, 0.9f, 0.8566667f).durability(6120)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> TIGER_TOMMY = registerWeapon("tiger_tommy", () -> new TigerTommy(GunStats.of(2.875f, 3, 0.7f, 0.85924244f).durability(5960)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> TOMMY = registerWeapon("tommy", () -> new Tommy(GunStats.of(1.5f, 3, 1.3f, 0.83090913f).durability(1320)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> VILE_VANQUISHER = registerWeapon("vile_vanquisher", () -> new VileVanquisher(GunStats.of(2.75f, 4, 1f, 0.84250003f).durability(3320)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> WART_GUN = registerWeapon("wart_gun", () -> new WartGun(GunStats.of(4.5375f, 7, 0.2f, 0.84007144f).durability(2320)), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredItem<Item> WRECKER = registerWeapon("wrecker", () -> new Wrecker(GunStats.of(2.375f, 3, 1.1f, 0.8489394f).durability(3680)), AoACreativeModeTabs.GUNS.getKey());
	
	public static final DeferredItem<Item> ABYSSRO = registerWeapon("abyssro", () -> new BaseShotgun(ShotgunStats.of(GunStats.of(18.5f, 46, 0.2f, 0.82486165f), 2, 0.3f).durability(1100)), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredItem<Item> AMPLIFIER = registerWeapon("amplifier", () -> new Amplifier(ShotgunStats.of(GunStats.of(9.0f, 56, 0.7f, 0.8099351f), 5, 0.2f).durability(1100)), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredItem<Item> BLAST_BARREL = registerWeapon("blast_barrel", () -> new BlastBarrel(ShotgunStats.of(GunStats.of(13.0f, 62, 0.4f, 0.8129619f), 3, 0.4f).durability(740)), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredItem<Item> BLUE_BARREL = registerWeapon("blue_barrel", () -> new BaseShotgun(ShotgunStats.of(GunStats.of(14.5f, 54, 0.4f, 0.81659937f), 3, 0.4f).durability(1120)), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredItem<Item> BOULDER = registerWeapon("boulder", () -> new BaseShotgun(ShotgunStats.of(GunStats.of(11.5f, 58, 0.5f, 0.81225705f), 4, 0.4f).durability(1080)), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredItem<Item> BROWN_BLASTER = registerWeapon("brown_blaster", () -> new BaseShotgun(ShotgunStats.of(GunStats.of(6.0f, 54, 0.9f, 0.8068687f), 3, 0.4f).durability(300)), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredItem<Item> DEMOLISHER = registerWeapon("demolisher", () -> new Demolisher(ShotgunStats.of(GunStats.of(8.5f, 58, 0.65f, 0.80905956f), 4, 0.4f).durability(730)), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredItem<Item> DESTRUCTION_SHOTGUN = registerWeapon("destruction_shotgun", () -> new DestructionShotgun(ShotgunStats.of(GunStats.of(10.5f, 56, 0.45f, 0.8115909f), 3, 0.4f).durability(690)), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredItem<Item> DISCHARGE_SHOTGUN = registerWeapon("discharge_shotgun", () -> new DischargeShotgun(ShotgunStats.of(GunStats.of(0.0f, 55, 13f, 0.8f), 4, 0f).durability(160)), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredItem<Item> GIMMICK = registerWeapon("gimmick", () -> new Gimmick(ShotgunStats.of(GunStats.of(4.5f, 68, 1.3f, 0.8040909f), 10, 0.2f).durability(800)), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredItem<Item> GINGER_BLASTER = registerWeapon("ginger_blaster", () -> new GingerBlaster(ShotgunStats.of(GunStats.of(7.0f, 60, 0.75f, 0.8072121f), 5, 0.4f).durability(720)), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredItem<Item> LONG_SHOT = registerWeapon("long_shot", () -> new LongShot(ShotgunStats.of(GunStats.of(15.5f, 54, 0.3f, 0.81774414f), 2, 0.2f).durability(730)), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredItem<Item> MECHYRO = registerWeapon("mechyro", () -> new Mechyro(ShotgunStats.of(GunStats.of(13.0f, 46, 0.3f, 0.8174704f), 2, 0.3f).durability(720)), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredItem<Item> PURITY_SHOTGUN = registerWeapon("purity_shotgun", () -> new PurityShotgun(ShotgunStats.of(GunStats.of(14.0f, 56, 0.25f, 0.81545454f), 3, 0.4f).durability(1090)), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredItem<Item> PURPLE_PUNISHER = registerWeapon("purple_punisher", () -> new BaseShotgun(ShotgunStats.of(GunStats.of(20.5f, 52, 0.2f, 0.8243706f), 2, 0.785f).durability(1120)), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredItem<Item> RED_ROCKET = registerWeapon("red_rocket", () -> new BaseShotgun(ShotgunStats.of(GunStats.of(11.5f, 52, 0.4f, 0.81367135f), 2, 0.785f).durability(500)), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredItem<Item> VIVO = registerWeapon("vivo", () -> new Vivo(ShotgunStats.of(GunStats.of(7.0f, 36, 0.8f, 0.81202024f), 3, 0.3f).durability(710)), AoACreativeModeTabs.SHOTGUNS.getKey());

	public static final DeferredItem<Item> BARON_SSR = registerWeapon("baron_ssr", () -> new BaronSSR(GunStats.of(35.0f, 88, 0.4f, 0.8245868f).durability(240)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> BAYONETTE_SR = registerWeapon("bayonette_sr", () -> new BayonetteSR(GunStats.of(33.0f, 86, 0.41f, 0.82372093f).durability(300).attributes(BayonetteSR.createAttributes())), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> BOLT_RIFLE = registerWeapon("bolt_rifle", () -> new BoltRifle(GunStats.of(30.0f, 100, 0.41f, 0.81854546f).durability(100)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> CAMO_RIFLE = registerWeapon("camo_rifle", () -> new CamoRifle(GunStats.of(31.5f, 84, 0.41f, 0.8231818f).durability(150)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> CLOWN_CRACKER = registerWeapon("clown_cracker", () -> new ClownCracker(GunStats.of(33.5f, 84, 0.4f, 0.8246537f).durability(305)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> CLOWNIMATOR = registerWeapon("clownimator", () -> new Clownimator(GunStats.of(49.5f, 95, 0.385f, 0.83221054f).durability(545)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> CRYSTANEER = registerWeapon("crystaneer", () -> new Crystaneer(GunStats.of(37.5f, 88, 0.392f, 0.826343f).durability(345)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> DARK_BEAST = registerWeapon("dark_beast", () -> new DarkBeast(GunStats.of(50.5f, 96, 0.385f, 0.83251894f).durability(560)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> DEADLOCK = registerWeapon("deadlock", () -> new Deadlock(GunStats.of(25.5f, 90, 0.44f, 0.81751513f).durability(120)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> DECIMATOR = registerWeapon("decimator", () -> new Decimator(GunStats.of(33.0f, 95, 0.4f, 0.8214737f).durability(180)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> DISCHARGE_SNIPER = registerWeapon("discharge_sniper", () -> new DischargeSniper(GunStats.of(10.0f, 24, 0.75f, 0.82575756f).durability(540)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> DUAL_SIGHT = registerWeapon("dual_sight", () -> new DualSight(GunStats.of(38.5f, 91, 0.392f, 0.8261539f).durability(350)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> DUSTER = registerWeapon("duster", () -> new Duster(GunStats.of(21.0f, 60, 0.44f, 0.8216364f).durability(170)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> FLORO500 = registerWeapon("floro500", () -> new Floro500(GunStats.of(37.0f, 70, 0.392f, 0.83267534f).durability(550)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> HEAD_HUNTER = registerWeapon("head_hunter", () -> new HeadHunter(GunStats.of(41.5f, 92, 0.385f, 0.8278854f).durability(380)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> HIVE_CRACKER = registerWeapon("hive_cracker", () -> new HiveCracker(GunStats.of(44.0f, 84, 0.385f, 0.83238095f).durability(555)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> KA_500 = registerWeapon("ka_500", () -> new Ka500(GunStats.of(30.0f, 70, 0.41f, 0.8264935f).durability(360)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> MARK_MAKER = registerWeapon("mark_maker", () -> new MarkMaker(GunStats.of(36.5f, 70, 0.385f, 0.8322338f).durability(530)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> MINERAL = registerWeapon("mineral", () -> new Mineral(GunStats.of(58.5f, 112, 0.385f, 0.832289f).durability(560)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> MONSTER = registerWeapon("monster", () -> new Monster(GunStats.of(38.0f, 96, 0.4f, 0.8244697f).durability(250)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> MOON_MAKER = registerWeapon("moon_maker", () -> new MoonMaker(GunStats.of(38.5f, 70, 0.4f, 0.834f).durability(570)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> ROSID_RIFLE = registerWeapon("rosid_rifle", () -> new RosidRifle(GunStats.of(45.5f, 102, 0.385f, 0.82757574f).durability(405)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> SABBATH = registerWeapon("sabbath", () -> new Sabbath(GunStats.of(44.0f, 97, 0.385f, 0.82804126f).durability(450)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> SLUDGE_SNIPER = registerWeapon("sludge_sniper", () -> new SludgeSniper(GunStats.of(37.0f, 87, 0.4f, 0.8262905f).durability(350)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> SWEET_TOOTH = registerWeapon("sweet_tooth", () -> new SweetTooth(GunStats.of(32.5f, 77, 0.4f, 0.8260921f).durability(460)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> TERMINATOR = registerWeapon("terminator", () -> new Terminator(GunStats.of(53.0f, 112, 0.385f, 0.82925326f).durability(470)), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredItem<Item> VIPER_1 = registerWeapon("viper_1", () -> new Viper1(GunStats.of(30.0f, 89, 0.41f, 0.8208376f).durability(185)), AoACreativeModeTabs.SNIPERS.getKey());

	public static final DeferredItem<Item> ANCIENT_BOMBER = registerWeapon("ancient_bomber", () -> new AncientBomber(GunStats.of(23.5f, 28, 0.175f, 0.8518831f).durability(855)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> ANCIENT_DISCHARGER = registerWeapon("ancient_discharger", () -> new AncientDischarger(GunStats.of(0.0f, 20, 13f, 0.8f).durability(850)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> AQUA_CANNON = registerWeapon("aqua_cannon", () -> new AquaCannon(GunStats.of(14.0f, 35, 0.21f, 0.8247273f).durability(300)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> BALLOON_BOMBER = registerWeapon("balloon_bomber", () -> new BalloonBomber(GunStats.of(12.5f, 24, 0.22f, 0.83219695f).durability(505)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> BIG_BLAST = registerWeapon("big_blast", () -> new BigBlast(GunStats.of(28.0f, 60, 0.12f, 0.8288485f).durability(550)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> BLAST_CANNON = registerWeapon("blast_cannon", () -> new BlastCannon(GunStats.of(17.0f, 27, 0.21f, 0.83892256f).durability(510)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> BLISSFUL_BLAST = registerWeapon("blissful_blast", () -> new BlissfulBlast(GunStats.of(33.5f, 60, 0.09f, 0.83451515f).durability(835)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> BOMB_LAUNCHER = registerWeapon("bomb_launcher", () -> new BombLauncher(GunStats.of(23.0f, 27, 0.175f, 0.85265994f).durability(840)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> BOOM_BOOM = registerWeapon("boom_boom", () -> new BoomBoom(GunStats.of(18.5f, 36, 0.21f, 0.8317677f).durability(390)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> BOOM_CANNON = registerWeapon("boom_cannon", () -> new BoomCannon(GunStats.of(17.5f, 28, 0.21f, 0.8386364f).durability(510)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> BOULDER_BOMBER = registerWeapon("boulder_bomber", () -> new BoulderBomber(GunStats.of(18.5f, 62, 0.21f, 0.81844574f).durability(475)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> BOZO_BLASTER = registerWeapon("bozo_blaster", () -> new BozoBlaster(GunStats.of(12.5f, 20, 0.21f, 0.8386364f).durability(505)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> BULB_CANNON = registerWeapon("bulb_cannon", () -> new BulbCannon(GunStats.of(25.0f, 30, 0.15f, 0.8515152f).durability(860)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> CARROT_CANNON = registerWeapon("carrot_cannon", () -> new CarrotCannon(GunStats.of(10.0f, 16, 0.4f, 0.8386364f).durability(520)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> CLOWN_CANNON = registerWeapon("clown_cannon", () -> new ClownCannon(GunStats.of(22.5f, 32, 0.18f, 0.8434659f).durability(570)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> CLOWNO_PULSE = registerWeapon("clowno_pulse", () -> new ClownoPulse(GunStats.of(35.5f, 42, 0.09f, 0.8522511f).durability(845)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> CORAL_CANNON = registerWeapon("coral_cannon", () -> new CoralCannon(GunStats.of(12.0f, 15, 0.35f, 0.8494546f).durability(300)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> DISCHARGE_CANNON = registerWeapon("discharge_cannon", () -> new DischargeCannon(GunStats.of(0.0f, 20, 6.0f, 0.8f).durability(400)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> ENERGY_CANNON = registerWeapon("energy_cannon", () -> new EnergyCannon(GunStats.of(18.5f, 25, 0.21f, 0.84574544f).durability(610)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> EREBON_STICKLER = registerWeapon("erebon_stickler", () -> new ErebonStickler(GunStats.of(35.0f, 48, 0.09f, 0.8450758f).durability(750)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> FLORO_RPG = registerWeapon("floro_rpg", () -> new FloroRPG(GunStats.of(18.0f, 50, 0.21f, 0.82225454f).durability(830)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> FLOWER_CANNON = registerWeapon("flower_cannon", () -> new FlowerCannon(GunStats.of(14.5f, 23, 0.21f, 0.83897233f).durability(510)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> FUNGAL_CANNON = registerWeapon("fungal_cannon", () -> new FungalCannon(GunStats.of(19.5f, 23, 0.2f, 0.8524111f).durability(850)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> GHAST_BLASTER = registerWeapon("ghast_blaster", () -> new GhastBlaster(GunStats.of(20.0f, 28, 0.2f, 0.84415585f).durability(600)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> GHOUL_CANNON = registerWeapon("ghoul_cannon", () -> new GhoulCannon(GunStats.of(25.5f, 34, 0.15f, 0.84636366f).durability(590)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> GIGA_CANNON = registerWeapon("giga_cannon", () -> new GigaCannon(GunStats.of(25.5f, 30, 0.15f, 0.85254544f).durability(700)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> GOLDER_BOMBER = registerWeapon("golder_bomber", () -> new GolderBomber(GunStats.of(26.0f, 62, 0.15f, 0.82592374f).durability(840)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> HIVE_BLASTER = registerWeapon("hive_blaster", () -> new HiveBlaster(GunStats.of(20.5f, 24, 0.2f, 0.85280305f).durability(850)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> HIVE_HOWITZER = registerWeapon("hive_howitzer", () -> new HiveHowitzer(GunStats.of(13.0f, 24, 0.35f, 0.8334849f).durability(375)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> IRO_CANNON = registerWeapon("iro_cannon", () -> new IroCannon(GunStats.of(25.5f, 36, 0.15f, 0.8437879f).durability(580)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> JACK_FUNGER = registerWeapon("jack_funger", () -> new JackFunger(GunStats.of(17.0f, 20, 0.21f, 0.85254544f).durability(860)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> JACK_ROCKER = registerWeapon("jack_rocker", () -> new JackRocker(GunStats.of(10.5f, 20, 0.4f, 0.83245456f).durability(400)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> LUXON_STICKLER = registerWeapon("luxon_stickler", () -> new LuxonStickler(GunStats.of(35.0f, 48, 0.09f, 0.8450758f).durability(750)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> MECHA_CANNON = registerWeapon("mecha_cannon", () -> new MechaCannon(GunStats.of(26.5f, 42, 0.15f, 0.83900434f).durability(525)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> MINI_CANNON = registerWeapon("mini_cannon", () -> new MiniCannon(GunStats.of(15.0f, 30, 0.21f, 0.83090913f).durability(415)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> MISSILE_MAKER = registerWeapon("missile_maker", () -> new MissileMaker(GunStats.of(0.0f, 60, 7f, 0.8f).durability(495)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> MOON_CANNON = registerWeapon("moon_cannon", () -> new MoonCannon(GunStats.of(21.0f, 25, 0.18f, 0.8519273f).durability(855)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> PLUTON_STICKLER = registerWeapon("pluton_stickler", () -> new PlutonStickler(GunStats.of(35.0f, 48, 0.09f, 0.8450758f).durability(750)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> PREDATORIAN_BLASTER = registerWeapon("predatorian_blaster", () -> new PredatorianBlaster(GunStats.of(23.5f, 28, 0.175f, 0.8518831f).durability(845)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> PULSE_CANNON = registerWeapon("pulse_cannon", () -> new PulseCannon(GunStats.of(26.0f, 42, 0.15f, 0.8382684f).durability(510)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> RPG = registerWeapon("rpg", () -> new RPG(GunStats.of(8.0f, 50, 0.35f, 0.8098909f).durability(320)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> SELYAN_STICKLER = registerWeapon("selyan_stickler", () -> new SelyanStickler(GunStats.of(35.0f, 48, 0.09f, 0.8450758f).durability(750)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> SHADOW_BLASTER = registerWeapon("shadow_blaster", () -> new ShadowBlaster(GunStats.of(15.0f, 24, 0.21f, 0.8386364f).durability(515)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> SHYRE_BLASTER = registerWeapon("shyre_blaster", () -> new ShyreBlaster(GunStats.of(25.5f, 30, 0.15f, 0.85254544f).durability(850)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> SMILE_BLASTER = registerWeapon("smile_blaster", () -> new SmileBlaster(GunStats.of(20.5f, 24, 0.2f, 0.85280305f).durability(840)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> SUPER_CANNON = registerWeapon("super_cannon", () -> new SuperCannon(GunStats.of(18.5f, 30, 0.21f, 0.83812124f).durability(510)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> ULTRA_CANNON = registerWeapon("ultra_cannon", () -> new UltraCannon(GunStats.of(22.5f, 30, 0.18f, 0.84636366f).durability(605)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> VOX_CANNON = registerWeapon("vox_cannon", () -> new VoxCannon(GunStats.of(15.0f, 26, 0.21f, 0.83566433f).durability(440)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> WATER_BALLOON_BOMBER = registerWeapon("water_balloon_bomber", () -> new WaterBalloonBomber(GunStats.of(20.5f, 24, 0.2f, 0.85280305f).durability(855)), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredItem<Item> WITHER_CANNON = registerWeapon("wither_cannon", () -> new WitherCannon(GunStats.of(17.0f, 30, 0.21f, 0.8350303f).durability(460)), AoACreativeModeTabs.CANNONS.getKey());

	public static final DeferredItem<Grenade> GRENADE = registerWeapon("grenade", () -> new Grenade(GunStats.of(0.0f, 10, 0, 0.5f).stacksTo(64)), AoACreativeModeTabs.THROWN_WEAPONS.getKey());
	public static final DeferredItem<SliceStar> SLICE_STAR = registerWeapon("slice_star", () -> new SliceStar(GunStats.of(4.5f, 7, 0, 0.5f).stacksTo(64)), AoACreativeModeTabs.THROWN_WEAPONS.getKey());
	public static final DeferredItem<Chakram> CHAKRAM = registerWeapon("chakram", () -> new Chakram(GunStats.of(4f, 7, 0, 0.5f).stacksTo(64)), AoACreativeModeTabs.THROWN_WEAPONS.getKey());
	public static final DeferredItem<GooBall> GOO_BALL = registerWeapon("goo_ball", () -> new GooBall(GunStats.of(3.5f, 7, 0, 0.5f).stacksTo(64)), AoACreativeModeTabs.THROWN_WEAPONS.getKey());
	public static final DeferredItem<Vulkram> VULKRAM = registerWeapon("vulkram", () -> new Vulkram(GunStats.of(3f, 7, 0, 0.5f).stacksTo(64)), AoACreativeModeTabs.THROWN_WEAPONS.getKey());
	public static final DeferredItem<Hellfire> HELLFIRE = registerWeapon("hellfire", () -> new Hellfire(GunStats.of(3.5f, 7, 0, 0.5f).stacksTo(64)), AoACreativeModeTabs.THROWN_WEAPONS.getKey());
	public static final DeferredItem<RunicBomb> RUNIC_BOMB = registerWeapon("runic_bomb", () -> new RunicBomb(GunStats.of(0.0f, 10, 0, 0.5f).stacksTo(64)), AoACreativeModeTabs.THROWN_WEAPONS.getKey());
	public static final DeferredItem<HardenedParapiranha> HARDENED_PARAPIRANHA = registerWeapon("hardened_parapiranha", () -> new HardenedParapiranha(GunStats.of(10, 20, 0, 0.5f).stacksTo(64)), AoACreativeModeTabs.THROWN_WEAPONS.getKey());

	public static final DeferredItem<Item> VULCANE = registerWeapon("vulcane", () -> new Vulcane(VulcaneStats.of(10).durability(50)), AoACreativeModeTabs.VULCANES.getKey());
	public static final DeferredItem<Item> BATTLE_VULCANE = registerWeapon("battle_vulcane", () -> new BattleVulcane(VulcaneStats.of(10).durability(75)), AoACreativeModeTabs.VULCANES.getKey());
	public static final DeferredItem<Item> EQUALITY_VULCANE = registerWeapon("equality_vulcane", () -> new EqualityVulcane(VulcaneStats.of(10).durability(75)), AoACreativeModeTabs.VULCANES.getKey());
	public static final DeferredItem<Item> FIRE_VULCANE = registerWeapon("fire_vulcane", () -> new FireVulcane(VulcaneStats.of(10).durability(75)), AoACreativeModeTabs.VULCANES.getKey());
	public static final DeferredItem<Item> IMPAIRMENT_VULCANE = registerWeapon("impairment_vulcane", () -> new ImpairmentVulcane(VulcaneStats.of(10).durability(75)), AoACreativeModeTabs.VULCANES.getKey());
	public static final DeferredItem<Item> POISON_VULCANE = registerWeapon("poison_vulcane", () -> new PoisonVulcane(VulcaneStats.of(10).durability(75)), AoACreativeModeTabs.VULCANES.getKey());
	public static final DeferredItem<Item> POWER_VULCANE = registerWeapon("power_vulcane", () -> new PowerVulcane(VulcaneStats.of(10).durability(75)), AoACreativeModeTabs.VULCANES.getKey());
	public static final DeferredItem<Item> WITHER_VULCANE = registerWeapon("wither_vulcane", () -> new WitherVulcane(VulcaneStats.of(10).durability(75)), AoACreativeModeTabs.VULCANES.getKey());
	
	public static final DeferredItem<Item> ALACRITY_BOW = registerWeapon("alacrity_bow", () -> new BaseBow(BowStats.of(9.5f, 1f).durability(600)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> ANCIENT_BOW = registerWeapon("ancient_bow", () -> new BaseBow(BowStats.of(22.0f, 1f).durability(1510)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> ATLANTIC_BOW = registerWeapon("atlantic_bow", () -> new BaseBow(BowStats.of(24.5f, 0.9f).durability(1480)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> BARON_BOW = registerWeapon("baron_bow", () -> new BaronBow(BowStats.of(12.0f, 1.1f).durability(3000)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> BOREIC_BOW = registerWeapon("boreic_bow", () -> new BoreicBow(BowStats.of(14.0f, 1.3f).durability(1190)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> DAYBREAKER_BOW = registerWeapon("daybreaker_bow", () -> new DaybreakerBow(BowStats.of(17.5f, 1f).durability(1180)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> DEEP_BOW = registerWeapon("deep_bow", () -> new DeepBow(BowStats.of(15.5f, 0.85f).durability(700)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> EXPLOSIVE_BOW = registerWeapon("explosive_bow", () -> new ExplosiveBow(BowStats.of(17.0f, 0.8f).durability(900)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> HAUNTED_BOW = registerWeapon("haunted_bow", () -> new HauntedBow(BowStats.of(17.0f,1f).durability(920)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> ICE_BOW = registerWeapon("ice_bow", () -> new IceBow(BowStats.of(8.5f, 1f).durability(580)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> INFERNAL_BOW = registerWeapon("infernal_bow", () -> new InfernalBow(BowStats.of(11.5f, 1f).durability(710)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> JUSTICE_BOW = registerWeapon("justice_bow", () -> new JusticeBow(BowStats.of(14.5f,1f).durability(920)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> LUNAR_BOW = registerWeapon("lunar_bow", () -> new LunarBow(BowStats.of(17.5f, 1f).durability(900)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> MECHA_BOW = registerWeapon("mecha_bow", () -> new BaseBow(BowStats.of(20.5f,0.75f).durability(930)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> NIGHTMARE_BOW = registerWeapon("nightmare_bow", () -> new NightmareBow(BowStats.of(13.5f,1f).durability(890)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> POISON_BOW = registerWeapon("poison_bow", () -> new PoisonBow(BowStats.of(15.0f, 1f).durability(950)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> PREDATIOUS_BOW = registerWeapon("predatious_bow", () -> new BaseBow(BowStats.of(14.0f, 0.9f).durability(690)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> PRIMORDIAL_BOW = registerWeapon("primordial_bow", () -> new PrimordialBow(BowStats.of(18.5f,1f).durability(1350)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> ROSIDIAN_BOW = registerWeapon("rosidian_bow", () -> new RosidianBow(BowStats.of(15.5f, 1f).durability(900)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> RUNIC_BOW = registerWeapon("runic_bow", () -> new RunicBow(BowStats.of(20.5f,1f).durability(1320)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> SCREAMER_BOW = registerWeapon("screamer_bow", () -> new ScreamerBow(BowStats.of(12.0f, 1f).durability(665)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> SHYREGEM_BOW = registerWeapon("shyregem_bow", () -> new ShyregemBow(BowStats.of(7.5f, 3.0f).durability(1500)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> SKELETAL_BOW = registerWeapon("skeletal_bow", () -> new BaseBow(BowStats.of(8.5f, 1.5f).durability(720)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> SKYDRIVER_BOW = registerWeapon("skydriver_bow", () -> new SkydriverBow(BowStats.of(14.5f, 1f).durability(850)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> SLINGSHOT = registerWeapon("slingshot", () -> new Slingshot(BowStats.of(17.0f, 1f).durability(1200)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> SOULFIRE_BOW = registerWeapon("soulfire_bow", () -> new SoulfireBow(BowStats.of(23.5f, 0.75f).durability(1100)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> SPECTRAL_BOW = registerWeapon("spectral_bow", () -> new SpectralBow(BowStats.of(12.0f, 1.3f).durability(900)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> SPEED_BOW = registerWeapon("speed_bow", () -> new BaseBow(BowStats.of(8.0f, 2).durability(930)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> SUNSHINE_BOW = registerWeapon("sunshine_bow", () -> new SunshineBow(BowStats.of(27.0f, 0.8f).durability(1530)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> TOXIN_BOW = registerWeapon("toxin_bow", () -> new ToxinBow(BowStats.of(14.0f, 0.85f).durability(900)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> VOID_BOW = registerWeapon("void_bow", () -> new BaseBow(BowStats.of(9.0f, 1.2f).durability(600)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> WEAKEN_BOW = registerWeapon("weaken_bow", () -> new WeakenBow(BowStats.of(12.5f, 1f).durability(700)), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredItem<Item> WITHER_BOW = registerWeapon("wither_bow", () -> new WitherBow(BowStats.of(13.5f, 1f).durability(835)), AoACreativeModeTabs.BOWS.getKey());
	
	public static final DeferredItem<Item> CORAL_CROSSBOW = registerWeapon("coral_crossbow", () -> new CoralCrossbow(CrossbowStats.of(17f).durability(1080)), AoACreativeModeTabs.CROSSBOWS.getKey());
	public static final DeferredItem<Item> LUNAR_CROSSBOW = registerWeapon("lunar_crossbow", () -> new LunarCrossbow(CrossbowStats.of(16.5f).durability(1100)), AoACreativeModeTabs.CROSSBOWS.getKey());
	public static final DeferredItem<Item> MECHA_CROSSBOW = registerWeapon("mecha_crossbow", () -> new BaseCrossbow(CrossbowStats.of(15f).durability(930)), AoACreativeModeTabs.CROSSBOWS.getKey());
	public static final DeferredItem<Item> PYRO_CROSSBOW = registerWeapon("pyro_crossbow", () -> new PyroCrossbow(CrossbowStats.of(12f).durability(800)), AoACreativeModeTabs.CROSSBOWS.getKey());
	public static final DeferredItem<Item> ROSIDIAN_CROSSBOW = registerWeapon("rosidian_crossbow", () -> new RosidianCrossbow(CrossbowStats.of(14.5f).durability(900)), AoACreativeModeTabs.CROSSBOWS.getKey());
	public static final DeferredItem<Item> SKELETAL_CROSSBOW = registerWeapon("skeletal_crossbow", () -> new BaseCrossbow(CrossbowStats.of(12.5f).durability(860)), AoACreativeModeTabs.CROSSBOWS.getKey());
	public static final DeferredItem<Item> SPECTRAL_CROSSBOW = registerWeapon("spectral_crossbow", () -> new SpectralCrossbow(CrossbowStats.of(15f).durability(1030)), AoACreativeModeTabs.CROSSBOWS.getKey());
	public static final DeferredItem<Item> TROLLS_CROSSBOW = registerWeapon("trolls_crossbow", () -> new BaseCrossbow(CrossbowStats.of(10.5f).durability(700)), AoACreativeModeTabs.CROSSBOWS.getKey());
	public static final DeferredItem<Item> VIRAL_CROSSBOW = registerWeapon("viral_crossbow", () -> new ViralCrossbow(CrossbowStats.of(11f).durability(780)), AoACreativeModeTabs.CROSSBOWS.getKey());

	public static final DeferredItem<Item> AMBER_STAFF = registerWeapon("amber_staff", () -> new AmberStaff(StaffRuneCost.of(AmberStaff.getDefaultRunes()).durability(900)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> AQUATIC_STAFF = registerWeapon("aquatic_staff", () -> new AquaticStaff(StaffRuneCost.of(AquaticStaff.getDefaultRunes()).durability(1220)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> ATLANTIC_STAFF = registerWeapon("atlantic_staff", () -> new AtlanticStaff(StaffRuneCost.of(AtlanticStaff.getDefaultRunes()).durability(1250)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> BARON_STAFF = registerWeapon("baron_staff", () -> new BaronStaff(StaffRuneCost.of(BaronStaff.getDefaultRunes()).durability(1200)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> CANDY_STAFF = registerWeapon("candy_staff", () -> new CandyStaff(StaffRuneCost.of(CandyStaff.getDefaultRunes()).durability(950)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> CELESTIAL_STAFF = registerWeapon("celestial_staff", () -> new CelestialStaff(StaffRuneCost.of(CelestialStaff.getDefaultRunes()).durability(1150)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> CONCUSSION_STAFF = registerWeapon("concussion_staff", () -> new ConcussionStaff(StaffRuneCost.of(ConcussionStaff.getDefaultRunes()).durability(1150)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> CORAL_STAFF = registerWeapon("coral_staff", () -> new CoralStaff(StaffRuneCost.of(CoralStaff.getDefaultRunes()).durability(950)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> CRYSTAL_STAFF = registerWeapon("crystal_staff", () -> new CrystalStaff(StaffRuneCost.of(CrystalStaff.getDefaultRunes()).durability(1230)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> CRYSTIK_STAFF = registerWeapon("crystik_staff", () -> new CrystikStaff(StaffRuneCost.of(CrystikStaff.getDefaultRunes()).durability(1140)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> CRYSTON_STAFF = registerWeapon("cryston_staff", () -> new CrystonStaff(StaffRuneCost.of(CrystonStaff.getDefaultRunes()).durability(1240)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> DESTRUCTION_STAFF = registerWeapon("destruction_staff", () -> new DestructionStaff(StaffRuneCost.of(DestructionStaff.getDefaultRunes()).durability(1170)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> EMBER_STAFF = registerWeapon("ember_staff", () -> new EmberStaff(StaffRuneCost.of(EmberStaff.getDefaultRunes()).durability(1400)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> EVERFIGHT_STAFF = registerWeapon("everfight_staff", () -> new EverfightStaff(StaffRuneCost.of(EverfightStaff.getDefaultRunes()).durability(1050)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> EVERMIGHT_STAFF = registerWeapon("evermight_staff", () -> new EvermightStaff(StaffRuneCost.of(EvermightStaff.getDefaultRunes()).durability(1050)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> FIRE_STAFF = registerWeapon("fire_staff", () -> new FireStaff(StaffRuneCost.of(FireStaff.getDefaultRunes()).durability(850)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> FIREFLY_STAFF = registerWeapon("firefly_staff", () -> new FireflyStaff(StaffRuneCost.of(FireflyStaff.getDefaultRunes()).durability(1230)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> FIRESTORM_STAFF = registerWeapon("firestorm_staff", () -> new FirestormStaff(StaffRuneCost.of(FirestormStaff.getDefaultRunes()).durability(990)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> FUNGAL_STAFF = registerWeapon("fungal_staff", () -> new FungalStaff(StaffRuneCost.of(FungalStaff.getDefaultRunes()).durability(1130)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> GHOUL_STAFF = registerWeapon("ghoul_staff", () -> new GhoulStaff(StaffRuneCost.of(GhoulStaff.getDefaultRunes()).durability(400)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> HAUNTERS_STAFF = registerWeapon("haunters_staff", () -> new HauntersStaff(StaffRuneCost.of(HauntersStaff.getDefaultRunes()).durability(1225)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> HIVE_STAFF = registerWeapon("hive_staff", () -> new HiveStaff(StaffRuneCost.of(HiveStaff.getDefaultRunes()).durability(1130)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> JOKER_STAFF = registerWeapon("joker_staff", () -> new JokerStaff(StaffRuneCost.of(JokerStaff.getDefaultRunes()).durability(300)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> LIGHTNING_STAFF = registerWeapon("lightning_staff", () -> new LightningStaff(StaffRuneCost.of(LightningStaff.getDefaultRunes()).durability(1070)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> LIGHTSHINE = registerWeapon("lightshine", () -> new Lightshine(StaffRuneCost.of(Lightshine.getDefaultRunes()).durability(700)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> LUNAR_STAFF = registerWeapon("lunar_staff", () -> new LunarStaff(StaffRuneCost.of(LunarStaff.getDefaultRunes()).durability(1250)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> LYONIC_STAFF = registerWeapon("lyonic_staff", () -> new LyonicStaff(StaffRuneCost.of(LyonicStaff.getDefaultRunes()).durability(1100)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> MECHA_STAFF = registerWeapon("mecha_staff", () -> new MechaStaff(StaffRuneCost.of(MechaStaff.getDefaultRunes()).durability(1110)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> METEOR_STAFF = registerWeapon("meteor_staff", () -> new MeteorStaff(StaffRuneCost.of(MeteorStaff.getDefaultRunes()).durability(1190)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> MOONLIGHT_STAFF = registerWeapon("moonlight_staff", () -> new MoonlightStaff(StaffRuneCost.of(MoonlightStaff.getDefaultRunes()).durability(1130)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> NATURE_STAFF = registerWeapon("nature_staff", () -> new NatureStaff(StaffRuneCost.of(NatureStaff.getDefaultRunes()).durability(1450)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> NIGHTMARE_STAFF = registerWeapon("nightmare_staff", () -> new NightmareStaff(StaffRuneCost.of(NightmareStaff.getDefaultRunes()).durability(1200)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> NOXIOUS_STAFF = registerWeapon("noxious_staff", () -> new NoxiousStaff(StaffRuneCost.of(NoxiousStaff.getDefaultRunes()).durability(1210)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> PHANTOM_STAFF = registerWeapon("phantom_staff", () -> new PhantomStaff(StaffRuneCost.of(PhantomStaff.getDefaultRunes()).durability(1060)), AoACreativeModeTabs.STAVES.getKey()); // TODO move to phantom?
	public static final DeferredItem<Item> POISON_STAFF = registerWeapon("poison_staff", () -> new PoisonStaff(StaffRuneCost.of(PoisonStaff.getDefaultRunes()).durability(850)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> POWER_STAFF = registerWeapon("power_staff", () -> new PowerStaff(StaffRuneCost.of(PowerStaff.getDefaultRunes()).durability(1010)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> PRIMORDIAL_STAFF = registerWeapon("primordial_staff", () -> new PrimordialStaff(StaffRuneCost.of(PrimordialStaff.getDefaultRunes()).durability(1230)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> REEF_STAFF = registerWeapon("reef_staff", () -> new ReefStaff(StaffRuneCost.of(ReefStaff.getDefaultRunes()).durability(1230)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> REJUVENATION_STAFF = registerWeapon("rejuvenation_staff", () -> new RejuvenationStaff(StaffRuneCost.of(RejuvenationStaff.getDefaultRunes()).durability(870)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> ROSIDIAN_STAFF = registerWeapon("rosidian_staff", () -> new RosidianStaff(StaffRuneCost.of(RosidianStaff.getDefaultRunes()).durability(1180)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> RUNIC_STAFF = registerWeapon("runic_staff", () -> new RunicStaff(StaffRuneCost.of(RunicStaff.getDefaultRunes()).durability(1000)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> SHADOWLORD_STAFF = registerWeapon("shadowlord_staff", () -> new ShadowlordStaff(StaffRuneCost.of(ShadowlordStaff.getDefaultRunes()).durability(1200)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> SHOW_STAFF = registerWeapon("show_staff", () -> new ShowStaff(StaffRuneCost.of(ShowStaff.getDefaultRunes()).durability(900)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> SHYRE_STAFF = registerWeapon("shyre_staff", () -> new ShyreStaff(StaffRuneCost.of(ShyreStaff.getDefaultRunes()).durability(1380)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> SKY_STAFF = registerWeapon("sky_staff", () -> new SkyStaff(StaffRuneCost.of(SkyStaff.getDefaultRunes()).durability(1480)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> STRIKER_STAFF = registerWeapon("striker_staff", () -> new StrikerStaff(StaffRuneCost.of(StrikerStaff.getDefaultRunes()).durability(850)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> SUN_STAFF = registerWeapon("sun_staff", () -> new SunStaff(StaffRuneCost.of(SunStaff.getDefaultRunes()).durability(960)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> SURGE_STAFF = registerWeapon("surge_staff", () -> new SurgeStaff(StaffRuneCost.of(SurgeStaff.getDefaultRunes()).durability(1270)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> TANGLE_STAFF = registerWeapon("tangle_staff", () -> new TangleStaff(StaffRuneCost.of(TangleStaff.getDefaultRunes()).durability(1140)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> ULTIMATUM_STAFF = registerWeapon("ultimatum_staff", () -> new UltimatumStaff(StaffRuneCost.of(UltimatumStaff.getDefaultRunes()).durability(750)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> UNDERWORLD_STAFF = registerWeapon("underworld_staff", () -> new UnderworldStaff(StaffRuneCost.of(UnderworldStaff.getDefaultRunes()).durability(1140)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> WARLOCK_STAFF = registerWeapon("warlock_staff", () -> new WarlockStaff(StaffRuneCost.of(WarlockStaff.getDefaultRunes()).durability(1050)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> WATER_STAFF = registerWeapon("water_staff", () -> new WaterStaff(StaffRuneCost.of(WaterStaff.getDefaultRunes()).durability(850)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> WEB_STAFF = registerWeapon("web_staff", () -> new WebStaff(StaffRuneCost.of(WebStaff.getDefaultRunes()).durability(1420)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> WIND_STAFF = registerWeapon("wind_staff", () -> new WindStaff(StaffRuneCost.of(WindStaff.getDefaultRunes()).durability(850)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> WITHER_STAFF = registerWeapon("wither_staff", () -> new WitherStaff(StaffRuneCost.of(WitherStaff.getDefaultRunes()).durability(850)), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredItem<Item> WIZARDS_STAFF = registerWeapon("wizards_staff", () -> new WizardsStaff(StaffRuneCost.of(WizardsStaff.getDefaultRunes()).durability(800)), AoACreativeModeTabs.STAVES.getKey());

	public static final DeferredItem<Item> APOCO_SHOWER = registerWeapon("apoco_shower", () -> new ApocoShower(BlasterStats.of(0.0f, 10, 80f, 10).durability(3760)), AoACreativeModeTabs.BLASTERS.getKey());// TODO
	public static final DeferredItem<Item> ATOMIZER = registerWeapon("atomizer", () -> new Atomizer(BlasterStats.of(11.0f, 8, 15f, 8).durability(3150)), AoACreativeModeTabs.BLASTERS.getKey());// TODO
	public static final DeferredItem<Item> BEAMER = registerWeapon("beamer", () -> new Beamer(BlasterStats.of(1.0f, 1, 3f, 1).durability(3240)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> BLAST_CHILLER = registerWeapon("blast_chiller", () -> new BlastChiller(BlasterStats.of(4.0f, 6, 20f, 20).durability(1750)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> BLOOD_DRAINER = registerWeapon("blood_drainer", () -> new BloodDrainer(BlasterStats.of(0.1f, 1, 2.5f, 1).durability(2750)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> BONE_BLASTER = registerWeapon("bone_blaster", () -> new BoneBlaster(BlasterStats.of(6.0f, 6, 20f, 6).durability(2430)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> BUBBLE_HORN = registerWeapon("bubble_horn", () -> new BubbleHorn(BlasterStats.of(11.0f, 8, 15.5f, 8).durability(3200)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> COLOUR_CANNON = registerWeapon("colour_cannon", () -> new ColourCannon(BlasterStats.of(45.0f, 40, 110f, 40).durability(1000).rarity(Rarity.EPIC)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> CONFETTI_CANNON = registerWeapon("confetti_cannon", () -> new ConfettiCannon(BlasterStats.of(0.0f, 10, 0f, 10).durability(1000)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> CONFETTI_CLUSTER = registerWeapon("confetti_cluster", () -> new ConfettiCluster(BlasterStats.of(0.0f, 5, 0f, 5).durability(1500)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> DARK_DESTROYER = registerWeapon("dark_destroyer", () -> new DarkDestroyer(BlasterStats.of(0.0f, 100, 80f, 100).durability(3180)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> DARKLY_GUSTER = registerWeapon("darkly_guster", () -> new DarklyGuster(BlasterStats.of(8.0f, 5, 7f, 5).durability(3790)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> DEATH_RAY = registerWeapon("death_ray", () -> new DeathRay(BlasterStats.of(19f, 12, 17f, 12).durability(3840)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> DOOM_BRINGER = registerWeapon("doom_bringer", () -> new DoomBringer(BlasterStats.of(0.0f, 3, 15.5f, 3).durability(2820)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> ERADICATOR = registerWeapon("eradicator", () -> new Eradicator(BlasterStats.of(1.0f, 1, 2f, 1).durability(2790)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> EXPERIMENT_W_801 = registerWeapon("experiment_w_801", () -> new ExperimentW801(BlasterStats.of(37.0f, 50, 90.0f, 50).durability(5000).rarity(Rarity.EPIC)), (ResourceKey<CreativeModeTab>[])null);
	public static final DeferredItem<Item> FLOWERCORNE = registerWeapon("flowercorne", () -> new Flowercorne(BlasterStats.of(2.5f, 4, 20f, 4).durability(2910)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> FRAGMENT = registerWeapon("fragment", () -> new Fragment(BlasterStats.of(3.0f, 2, 2.5f, 2).durability(3830)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> FROSTER = registerWeapon("froster", () -> new Froster(BlasterStats.of(3.5f, 3, 7.5f, 3).durability(2800)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> GAS_BLASTER = registerWeapon("gas_blaster", () -> new GasBlaster(BlasterStats.of(0.0f, 1, 0.5f, 1).durability(2860)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> GHOUL_GASSER = registerWeapon("ghoul_gasser", () -> new GhoulGasser(BlasterStats.of(0.0f, 1, 1f, 1).durability(3210)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> GOLD_BRINGER = registerWeapon("gold_bringer", () -> new GoldBringer(BlasterStats.of(0.0f, 3, 12.5f, 3).durability(3830)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> GRAVITY_BLASTER = registerWeapon("gravity_blaster", () -> new GravityBlaster(BlasterStats.of(4.0f, 1, 120f, 1).durability(600)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> HELL_HORN = registerWeapon("hell_horn", () -> new HellHorn(BlasterStats.of(12.5f, 8, 11.5f, 8).durability(3800)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> ILLUSION_REVOLVER = registerWeapon("illusion_revolver", () -> new IllusionRevolver(BlasterStats.of(14.0f, 10, 20f, 10).durability(3200)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> ILLUSION_SMG = registerWeapon("illusion_smg", () -> new IllusionSMG(BlasterStats.of(4.0f, 3, 7f, 3).durability(3240)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> ION_BLASTER = registerWeapon("ion_blaster", () -> new IonBlaster(BlasterStats.of(13.0f, 11, 28.5f, 11).durability(2810)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> IRO_MINER = registerWeapon("iro_miner", () -> new IroMiner(BlasterStats.of(4.0f, 4, 7f, 4).durability(3060)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> LASER_BLASTER = registerWeapon("laser_blaster", () -> new LaserBlaster(BlasterStats.of(1.2f, 1, 2.5f, 20).durability(2840)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> LIGHT_BLASTER = registerWeapon("light_blaster", () -> new LightBlaster(BlasterStats.of(22.5f, 14, 20.5f, 14).durability(3810)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> LIGHT_SPARK = registerWeapon("light_spark", () -> new LightSpark(BlasterStats.of(0.0f, 1, 0f, 10).durability(7)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> LUNA_BLASTER = registerWeapon("luna_blaster", () -> new LunaBlaster(BlasterStats.of(3.0f, 2, 4f, 2).durability(3200)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> MECHA_BLASTER = registerWeapon("mecha_blaster", () -> new MechaBlaster(BlasterStats.of(36.0f, 30, 80f, 30).durability(2770)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> MIND_BLASTER = registerWeapon("mind_blaster", () -> new MindBlaster(BlasterStats.of(19.5f, 14, 27.5f, 14).durability(3180)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> MOON_DESTROYER = registerWeapon("moon_destroyer", () -> new MoonDestroyer(BlasterStats.of(0.0f, 100, 60f, 100).durability(3750)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> MOON_SHINER = registerWeapon("moon_shiner", () -> new MoonShiner(BlasterStats.of(3.5f, 5, 17.5f, 5).durability(1810)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> ODIOUS = registerWeapon("odious", () -> new Odious(BlasterStats.of(1.0f, 1, 1.5f, 1).durability(3190)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> ORBOCRON = registerWeapon("orbocron", () -> new Orbocron(BlasterStats.of(18.5f, 13, 26.5f, 13).durability( 3230)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> PARALYZER = registerWeapon("paralyzer", () -> new Paralyzer(BlasterStats.of(1.5f, 1, 1.5f, 1).durability(3900)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> PARTY_POPPER = registerWeapon("party_popper", () -> new PartyPopper(BlasterStats.of(1.5f, 1, 3f, 1).durability(2810)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> POISON_PLUNGER = registerWeapon("poison_plunger", () -> new PoisonPlunger(BlasterStats.of(0.0f, 20, 50f, 20).durability(2600)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> POWER_RAY = registerWeapon("power_ray", () -> new PowerRay(BlasterStats.of(12.5f, 12, 38.5f, 12).durability(2490)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> PROTON = registerWeapon("proton", () -> new Proton(BlasterStats.of(2.5f, 2, 4.5f, 2).durability(3000)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> REEFER = registerWeapon("reefer", () -> new Reefer(BlasterStats.of(5.0f, 4, 7f, 4).durability(3600)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> REVOLUTION = registerWeapon("revolution", () -> new Revolution(BlasterStats.of(0.0f, 20, 66f, 20).durability(2800)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> SEAOCRON = registerWeapon("seaocron", () -> new Seaocron(BlasterStats.of(20.5f, 13, 18.5f, 13).durability(3800)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> SKULLO_BLASTER = registerWeapon("skullo_blaster", () -> new SkulloBlaster(BlasterStats.of(3.5f, 2, 3f, 2).durability(3780)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> SOUL_DRAINER = registerWeapon("soul_drainer", () -> new SoulDrainer(BlasterStats.of(0.2f, 1, 2f, 1).durability(3770)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> SOUL_SPARK = registerWeapon("soul_spark", () -> new SoulSpark(BlasterStats.of(0.0f, 1, 0f, 20).durability(5)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> SOUL_STORM = registerWeapon("soul_storm", () -> new SoulStorm(BlasterStats.of(1.5f, 1, 2f, 1).durability(3190)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> SPIRIT_SHOWER = registerWeapon("spirit_shower", () -> new SpiritShower(BlasterStats.of(0.0f, 10, 100f, 10).durability(2870)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> SWARMOTRON = registerWeapon("swarmotron", () -> new Swarmotron(BlasterStats.of(2.0f, 12, 33f, 12).durability(2400)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> TOXIC_TERRORIZER = registerWeapon("toxic_terrorizer", () -> new ToxicTerrorizer(BlasterStats.of(0.0f, 7, 22f, 7).durability(2760)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> VORTEX_BLASTER = registerWeapon("vortex_blaster", () -> new VortexBlaster(BlasterStats.of(0.0f, 1, 130f, 1).durability(2870)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> WHIMSY_WINDER = registerWeapon("whimsy_winder", () -> new WhimsyWinder(BlasterStats.of(6.0f, 5, 13f, 5).durability(2830)), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredItem<Item> WITHERS_WRATH = registerWeapon("withers_wrath", () -> new WithersWrath(BlasterStats.of(7.5f, 7, 21f, 7).durability(800)), AoACreativeModeTabs.BLASTERS.getKey());

	private static <T extends Item> DeferredItem<T> registerWeapon(String registryName, Supplier<T> item, @Nullable ResourceKey<CreativeModeTab>... creativeTabs) {
		return AoAItems.registerItem(registryName, item, creativeTabs);
	}
}
